# Generated by Django 2.2.15 on 2020-08-29 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='品牌')),
                ('date', models.DateField(auto_now=True, verbose_name='更改日期')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='标题')),
                ('details', mdeditor.fields.MDTextField()),
                ('date', models.DateField(auto_now=True, verbose_name='更改日期')),
            ],
            options={
                'verbose_name': '经验',
                'verbose_name_plural': '经验',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='供应商')),
                ('tel', models.CharField(blank=True, max_length=256, null=True, verbose_name='优势品牌')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='联系手机')),
                ('date', models.DateField(auto_now=True, verbose_name='更改日期')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='分类')),
                ('date', models.DateField(auto_now=True, verbose_name='更改日期')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='单位')),
                ('date', models.DateField(auto_now=True, verbose_name='更改日期')),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gmodel', models.CharField(max_length=64, unique=True, verbose_name='品名规格')),
                ('price', models.FloatField(default=0, verbose_name='产品进价')),
                ('min_price', models.FloatField(default=0, verbose_name='最低售价')),
                ('meno', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('date', models.DateField(auto_now=True, verbose_name='更改日期')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Brand', verbose_name='品牌')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Supplier', verbose_name='供应商')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Type', verbose_name='分类')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Unit', verbose_name='单位')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品信息',
            },
        ),
    ]
